spring:
  application:
    name: artistry

  servlet:
    multipart:
      max-file-size: 20MB # 최대 파일 사이즈
      max-request-size: 20MB # 최대 요청 사이즈

  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL;
    driver-class-name: org.h2.Driver
    username: sa
    password:

    test:
      database:
        replace: NONE

    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      hibernate:
        ddl-auto: validate
      generate-ddl: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MYSQL5Dialect
          show_sql: false
          format_sql: true
          use_sql_comment: false

  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_ACCESS_KEY}
      region:
        static: ap-northeast-2
      s3:
        bucket: ${AWS_BUCKET_NAME}

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

springdoc:
  swagger-ui:
    url: /docs/openapi-3.0.json
    path: /docs/swagger

server:
  port=0:


  servlet:
    session:
      cookie:
        same-site: none
        secure : true

oauth:
  google:
    redirect_uri: ${GOOGLE_REDIRECT_URI}
    client_id: ${GOOGLE_CLIENT_ID}
    client_secret: ${GOOGLE_CLIENT_SECRET}
    token_uri: https://oauth2.googleapis.com/token

  naver:
    redirect_uri: ${NAVER_REDIRECT_URI}
    authorization_uri: https://nid.naver.com/oauth2.0/authorize
    token_uri: nid.naver.com/oauth2.0/token
    user_info_uri: https://openai.naver.com/v1/nid/me
    user_name-attribute: response
    client_secret: ${NAVER_CLIENT_SECRET}
    client_id : ${NAVER_CLIENT_ID}
    state : ${NAVER_STATE}

security:
  jwt:
    token:
      secret-key: mysecretkeyasdgasdgsadgsdagsdagagsagsagsag
      expire-length: 3600


AWS:
  ACCESS_KEY: ${AWS_ACCESS_KEY}
  SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
  BUCKET_NAME: ${AWS_BUCKET_NAME}