spring:


  application:
    name: artistry

  datasource:
    url : jdbc:mysql://localhost:3306/artistrydb?serverTimezone=UTC&characterEncoding=UTF-8
    username : root
    password : root
    driver-class-name: com.mysql.jdbc.Driver

  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_ACCESS_KEY}
      region: ap-northeast-2
      s3:
        bucket: ${AWS_BUCKET_NAME}

  servlet:
    multipart:
      max-file-size: 4MB # 최대 파일 사이즈
      max-request-size: 4MB # 최대 요청 사이즈


springdoc:
  swagger-ui:
    url: /docs/openapi-3.0.json
    path: /docs/swagger

server:
  port=0:
  servlet:
    session:
      cookie:
        same-site: none
        secure : true

oauth:
  google:
    redirect_uri: ${GOOGLE_REDIRECT_URI}
    client_id: ${GOOGLE_CLIENT_ID}
    client_secret: ${GOOGLE_CLIENT_SECRET}
    token_uri: https://oauth2.googleapis.com/token

  naver:
    redirect_uri: ${NAVER_REDIRECT_URI}
    authorization_uri: https://nid.naver.com/oauth2.0/authorize
    token_uri: nid.naver.com/oauth2.0/token
    user_info_uri: https://openai.naver.com/v1/nid/me
    user_name-attribute: response
    client_secret: ${NAVER_CLIENT_SECRET}
    client_id : ${NAVER_CLIENT_ID}
    state : ${NAVER_STATE}

security:
  jwt:
    token:
      secret-key: mysecretkeyasdgasdgsadgsdagsdagagsagsagsag
      expire-length: 3600
