spring:
  datasource:
    url : jdbc:mysql://artistrydb.crqcq8u4go3o.ap-northeast-2.rds.amazonaws.com:3306/artistrydb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username : admin
    password : ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update


AWS_ACCESS_KEY: ${AWS_ACCESS_KEY}
AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}