spring:
  datasource:
    url : jdbc:mysql://artistrydb.crqcq8u4go3o.ap-northeast-2.rds.amazonaws.com:3306/artistrydb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username : admin
    password : ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 3000
      validation-timeout: 3000
      minimum-idle: 5
      max-lifetime: 240000
      maximum-pool-size: 10

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update


AWS_ACCESS_KEY: ${AWS_ACCESS_KEY}
AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}

server:
  tomcat:
    accept-count: 10
    maxThread: 50
    connection-timeout: 20000ms
    maxKeepAliveRequests: 100
    keepAliveTimeout: 5000

logging:
  level:
    org.hibernate.SQL: info
    root: info
    com.zaxxer.hikari.pool.HikariPool: debug