spring:
  datasource:
    url : jdbc:mysql://localhost:3306/artistrydb?serverTimezone=UTC&characterEncoding=UTF-8
    username : root
    password : root
    driver-class-name: com.mysql.jdbc.Driver

  test:
    database:
      replace: NONE

    jpa:
      database-platform: org.hibernate.dialect.MySQLDialect
      hibernate:
        ddl-auto: validate
      generate-ddl: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQLDialect
          show_sql: false
          format_sql: true
          use_sql_comment: false