spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false

  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL;
    driver-class-name: org.h2.Driver
    username: sa
    password:

    database:
      replace: NONE

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
    ddl-auto: validate
    generate-ddl: true
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
      show_sql: false
      format_sql: true
      use_sql_comment: false

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG