spring:
  datasource:
    url : jdbc:mysql://43.203.1.139:3306/artistrydb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username : ${MYSQL_USER}
    password : ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8InnoDBDialect
    hibernate:
      ddl-auto: update


AWS_ACCESS_KEY: ${AWS_ACCESS_KEY}
AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}