spring:
  datasource:
    url : jdbc:mysql://{SPRING_DATASOURCE_URL}:3306/artistrydb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username : ${MYSQL_USER}
    password : ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQLDialect

AWS_ACCESS_KEY: ${AWS_ACCESS_KEY}
AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}