spring:
  datasource:
    url : jdbc:mysql://${SPRING_DATASOURCE_URL}/artistrydb
    username : ${MYSQL_USER}
    password : ${MYSQL_PASSWORD}
    driver-class-name: org.mysql.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true