spring:
  datasource:
    url : jdbc:mysql://${SPRING_DATASOURCE_URL}/artistrydb
    username : ${MYSQL_USER}
    password : ${MYSQL_PASSWORD}
    driver-class-name: org.mysql.jdbc.Driver

  test:
    database:
      replace: NONE

  jpa:
    hibernate:
      ddl-auto: validate

cloud:
  aws:
    region:
      static: ap-northeast-2