# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout
  checks: write
  pull-requests: write
  
on:
  push:
    branches: [ "master", "feat/*" ]
  pull_request:
    branches: [ "master", "feat/*"  ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::549201086101:role/artistryaces
        aws-region: ap-northeast-2

    - name: Set environment variables
      run: |
        echo "AWS_ACCESS_KEY=${{ secrets.AWS_ACCESS_KEY }}" >> $GITHUB_ENV
        echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV


    - name: Build with Maven
      run: mvn package -f pom.xml -Pdev
      env:
        IMAGE_NAME: ${{ secrets.DOCKER_HUB_IMAGENAME }}
        GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
        GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
        GOOGLE_REDIRECT_URI: ${{ secrets.GOOGLE_REDIRECT_URI }}
        NAVER_CLIENT_ID: ${{ secrets.NAVER_CLIENT_ID }}
        NAVER_CLIENT_SECRET: ${{ secrets.NAVER_CLIENT_SECRET }}
        NAVER_REDIRECT_URI: ${{ secrets.NAVER_REDIRECT_URI }}
        AWS_ACCESS_KEY: ${{secrets.AWS_ACCESS_KEY}}
        AWS_SECRET_ACCESS_KEY: ${{secrets.SECRET_ACCESS_KEY}}
        AWS_BUCKET_NAME: ${{secrets.AWS_BUCKET_NAME}}

    - name: Run the Maven verify phase
      run: mvn --batch-mode --update-snapshots verify

    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2.16.1
      if: always()
      with:
        files: "target/surefire-reports/*.xml"
