# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

permissions:
  checks: write
  pull-requests: write
  
on:
  push:
    branches: [ "master", "feat/*" ]
  pull_request:
    branches: [ "master", "feat/*"  ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
        
    - name: Verify Environment Variables
      run: |
        if [ -z "$GOOGLE_CLIENT_ID" ]; then echo "GOOGLE_CLIENT_ID is not set"; else echo "GOOGLE_CLIENT_ID is set"; fi
        if [ -z "$GOOGLE_CLIENT_SECRET" ]; then echo "GOOGLE_CLIENT_SECRET is not set"; else echo "GOOGLE_CLIENT_SECRET is set"; fi
        if [ -z "$GOOGLE_REDIRECT_URI" ]; then echo "GOOGLE_REDIRECT_URI is not set"; else echo "GOOGLE_REDIRECT_URI is set"; fi
        if [ -z "$NAVER_CLIENT_ID" ]; then echo "NAVER_CLIENT_ID is not set"; else echo "NAVER_CLIENT_ID is set"; fi
        if [ -z "$NAVER_CLIENT_SECRET" ]; then echo "NAVER_CLIENT_SECRET is not set"; else echo "NAVER_CLIENT_SECRET is set"; fi
        if [ -z "$NAVER_REDIRECT_URI" ]; then echo "NAVER_REDIRECT_URI is not set"; else echo "NAVER_REDIRECT_URI is set"; fi
      env:
        GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
        GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
        GOOGLE_REDIRECT_URI: ${{ secrets.GOOGLE_REDIRECT_URI }}
        NAVER_CLIENT_ID: ${{ secrets.NAVER_CLIENT_ID }}
        NAVER_CLIENT_SECRET: ${{ secrets.NAVER_CLIENT_SECRET }}
        NAVER_REDIRECT_URI: ${{ secrets.NAVER_REDIRECT_URI }}
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Run the Maven verify phase
      run: mvn --batch-mode --update-snapshots verify

    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2.16.1
      if: always()
      with:
        files: "target/surefire-reports/*.xml"
